# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyK8s < Formula
  desc "A lazygit-style terminal UI for Kubernetes"
  homepage "https://github.com/Starlexxx/lazy-k8s"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.4.0/lazy-k8s_0.4.0_darwin_amd64.tar.gz"
      sha256 "6d96e8c87fef9d19ed7721be0d9ca363b0e78af8185f5934961a7890ce454177"

      define_method(:install) do
        bin.install "lazy-k8s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.4.0/lazy-k8s_0.4.0_darwin_arm64.tar.gz"
      sha256 "8fe6198a49a768f6709d63ba7e0ba020b44a489adb9646669ac2627041abf6c3"

      define_method(:install) do
        bin.install "lazy-k8s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.4.0/lazy-k8s_0.4.0_linux_amd64.tar.gz"
      sha256 "489c24acad17d22de80b71bb5538d6fe1f57fc41b780e59d56474caaaf867f00"
      define_method(:install) do
        bin.install "lazy-k8s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.4.0/lazy-k8s_0.4.0_linux_arm64.tar.gz"
      sha256 "f2638bac27f08b99e22e1afb842c2d3769696398c3d9bf66aeb6a6790059bcfb"
      define_method(:install) do
        bin.install "lazy-k8s"
      end
    end
  end

  test do
    system "#{bin}/lazy-k8s", "--version"
  end
end
