# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyK8s < Formula
  desc "A lazygit-style terminal UI for Kubernetes"
  homepage "https://github.com/Starlexxx/lazy-k8s"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.3.1/lazy-k8s_0.3.1_darwin_amd64.tar.gz"
      sha256 "6506473b65e4034b45834e68b178bfe233b00b40ce95a659500f718f2e626605"

      def install
        bin.install "lazy-k8s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.3.1/lazy-k8s_0.3.1_darwin_arm64.tar.gz"
      sha256 "5f3c94faf020613e726feabe1c6954acd7ccc959a06ecbb23b894fa045c73845"

      def install
        bin.install "lazy-k8s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.3.1/lazy-k8s_0.3.1_linux_amd64.tar.gz"
      sha256 "ff4589233d8e93ae6d4a3905d43deb715cca5c40ea00f535dd9ca3e3d4cb5c9a"
      def install
        bin.install "lazy-k8s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.3.1/lazy-k8s_0.3.1_linux_arm64.tar.gz"
      sha256 "2642e4a48658990757a366378385983cd39dc067cd5d5fc44139cf5d45a05db9"
      def install
        bin.install "lazy-k8s"
      end
    end
  end

  test do
    system "#{bin}/lazy-k8s", "--version"
  end
end
