# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyK8s < Formula
  desc "A lazygit-style terminal UI for Kubernetes"
  homepage "https://github.com/Starlexxx/lazy-k8s"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.3.0/lazy-k8s_0.3.0_darwin_amd64.tar.gz"
      sha256 "fe3bcaf7b214bfeaf4721c1deeed97f50dbde317935748b5e4a3c493608afce7"

      def install
        bin.install "lazy-k8s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.3.0/lazy-k8s_0.3.0_darwin_arm64.tar.gz"
      sha256 "e46280b7f7a9d767c8de175e0fa3dd61b1d09cb188a07c99ab3e069f55b3eaf0"

      def install
        bin.install "lazy-k8s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.3.0/lazy-k8s_0.3.0_linux_amd64.tar.gz"
      sha256 "543cf02aa38f4ace85ace54e266696e229e867704da016a93d144e4dfeaebc78"
      def install
        bin.install "lazy-k8s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Starlexxx/lazy-k8s/releases/download/v0.3.0/lazy-k8s_0.3.0_linux_arm64.tar.gz"
      sha256 "43f73ab0b6a32478b1b5b8b42a5d485ba88940ed66a0f768ae336dcf93c9820a"
      def install
        bin.install "lazy-k8s"
      end
    end
  end

  test do
    system "#{bin}/lazy-k8s", "--version"
  end
end
